version: "3.8"
volumes:
  mysql:
  vendor:
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
